<?php

namespace app\controllers;

use app\models\ProductList;
use yii\web\Response;
use Yii;

class ProductController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }
    
    public function beforeAction($action)
    {
	    $this->enableCsrfValidation = false;
	    return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
	
	public function actionNew(){
	    Yii::$app->response->format = Response::FORMAT_JSONP;
    	$request = Yii::$app->request;
    	$model = new ProductList();
    	$model->site = $request->get('site');
    	$model->product_name = $request->get('product_name');
	    $model->product_url = $request->get('product_url');
    	$model->price = $request->get('price');
	    $model->content = $request->get('content');
	    if($model->save()){
	    	return ['status'=>true];
	    }else{
	    	return ['status'=>false, 'msg'=>$model->getErrors()];
	    }
    }

}

